# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3376ae56906762eea99d68da5df6a31bcb2d9e41a3af46710ad5a7c0799999e3514531b6e34a4029cd0a4f19694681881c948b7ca719be58cad9c4125a98757

test:
  secret_key_base: cbc10cded408a9e8b126704a3eb2efaa7b493a5f5b34a494f06b0fc8dc3a18af95ea882c9ad420c779677e2f812138dcba0acca5cc83a5f2b36345d1b64c4885

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
